services:
  whoami:
    build:
      context: ./apps/whoami
      dockerfile: Dockerfile
    container_name: whoami
    restart: always
    volumes:
      - identity:/var/data
    environment:
      VIRTUAL_HOST: "whoami.${DOMAIN:-localhost}"
      WITH_AUTH_HEADERS: true
    depends_on:
      - mongodb
    expose:
      - "3000"
      
  shorty-webserver:
    image: nginx:latest
    container_name: shorty-webserver
    restart: always
    volumes:
      - www:/var/www
      - ./nginx/shorty.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: "shorty.${DOMAIN:-localhost}"
      WITH_AUTH: true
    expose:
      - "80"

volumes:
  identity: