version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
    command: /bin/sh -c "chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh nginx -g 'daemon off;'"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    depends_on:
      - app
      - api
      - whois
    networks:
      - jk-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: packages/apps/app/Dockerfile
      args:
        - API_URL=http://api.${DOMAIN:-localhost}/api
        - WHOIS_URL=http://whois.${DOMAIN:-localhost}/api
    depends_on:
      - api
    networks:
      - jk-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: packages/services/api/Dockerfile
    depends_on:
      - whois
    networks:
      - jk-network
    environment:
      - NODE_ENV=production

  whois:
    container_name: whois
    build:
      context: .
      dockerfile: packages/services/whois/Dockerfile
    networks:
      - jk-network
    environment:
      - NODE_ENV=production

networks:
  jk-network:
    driver: bridge
