services:

  artifact-server:
    build:
      context: tests/artifact-server
      dockerfile: Dockerfile
    container_name: artifact-server-test
    environment:
      VIRTUAL_HOST: "artifacts.${DOMAIN:-localhost}"
    volumes:
      - ./tests/artifact-server/artifacts:/var/www
    expose:
      - 3001
    restart: always
    depends_on:
      - webhook-service

volumes:
  www-artifacts: