services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.nginx-proxy.nginx"
    networks:
      - jk-network

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"
    networks:
      - jk-network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${EMAIL:-admin@example.com}
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - jk-network

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://auth.${DOMAIN:-localhost}/oauth2/callback
      - VIRTUAL_HOST=auth.${DOMAIN:-localhost}
      - VIRTUAL_PORT=4180
      - LETSENCRYPT_HOST=auth.${DOMAIN:-localhost}
    expose:
      - "4180"
    networks:
      - jk-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: packages/apps/app/Dockerfile
      args:
        - API_URL=https://api.${DOMAIN:-localhost}/api
        - WHOIS_URL=https://whois.${DOMAIN:-localhost}/api
    environment:
      - LETSENCRYPT_HOST=${DOMAIN:-localhost}
      - VIRTUAL_HOST=${DOMAIN:-localhost}
      - VIRTUAL_PORT=80
    expose:
      - "80"
    depends_on:
      - api
      - whois
    networks:
      - jk-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: packages/services/api/Dockerfile
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - LETSENCRYPT_HOST=api.${DOMAIN:-localhost}
      - VIRTUAL_HOST=api.${DOMAIN:-localhost}
      - VIRTUAL_PORT=3001
    networks:
      - jk-network

  whois:
    container_name: whois
    build:
      context: .
      dockerfile: packages/services/whois/Dockerfile
    expose:
      - "3002"
    environment:
      - NODE_ENV=production
      - LETSENCRYPT_HOST=whois.${DOMAIN:-localhost}
      - VIRTUAL_HOST=whois.${DOMAIN:-localhost}
      - VIRTUAL_PORT=3002
    networks:
      - jk-network

networks:
  jk-network:
    driver: bridge

volumes:
  html:
  certs:
  acme:
  vhost:
  conf:
