# traefik.yml
api:
  dashboard: true
  insecure: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: jens.klimke@rwth-aachen.de
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web