server {
    listen 80;
    server_name localhost;

    # Root directory for serving files
    root /var/www/shorty/html;
    index index.html index.htm;

    # Logging
    access_log /var/log/nginx/shorty-access.log;
    error_log /var/log/nginx/shorty-error.log;

    # Serve static files
    location / {
        try_files $uri $uri/ =404;
    }
}