server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name auth.marlene.cloud;

    # SSL configuration
    ssl_certificate /etc/letsencrypt/live/auth.marlene.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/auth.marlene.cloud/privkey.pem;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Reverse proxy configuration
    location / {
        # General headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://auth:80/;
    }

    # Health check endpoint
    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}