# Default server configuration
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Redirect all unknown hosts to a 404 page
    location / {
        return 404;
    }
}