# Default server configuration
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Custom error pages
    error_page 404 /404.html;
    error_page 500 502 503 504 /500.html;

    # Location for error pages
    location ~ ^/(404|500|503)\.html$ {
        root /usr/share/nginx/html;
        internal;
    }

    # Redirect all unknown hosts to a 404 page
    location / {
        return 404;
    }
}

# Default server configuration for HTTPS
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    # Self-signed certificate for default server
    ssl_certificate /etc/letsencrypt/live/default/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/default/privkey.pem;

    # Custom error pages
    error_page 404 /404.html;
    error_page 500 502 504 /500.html;
    error_page 503 /503.html;

    # Location for error pages
    location ~ ^/(404|500|503)\.html$ {
        root /usr/share/nginx/html;
        internal;
    }

    # Redirect all unknown hosts to a 503 page
    location / {
        return 503;
    }
}
