server {
    listen 80;
    server_name whoami.localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Include common OAuth2 configuration
    include /etc/nginx/conf.d/oauth2.conf.incl;

    location / {
        # Auth request
        auth_request /oauth2/auth;
        error_page 401 =403 /oauth2/sign_in;

        # Cookie refresh handling
        auth_request_set $auth_cookie $upstream_http_set_cookie;
        add_header Set-Cookie $auth_cookie;

        proxy_pass http://whoami:8000;
    }
}
